name: Build Calculator App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: List directory contents
      run: dir
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.4.2
        pip install pyinstaller==6.3.0
    
    - name: Show Python version and installed packages
      run: |
        python --version
        pip list
    
    - name: List files before build
      run: dir
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --onefile --name "Calculator" calculator_qt.py
    
    - name: List files after build
      run: |
        dir
        dir dist
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Calculator-Windows
        path: dist/Calculator.exe
        retention-days: 5
