name: Build Calculator App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.4.2
        pip install pyinstaller==6.3.0
        pip install pkgutil-resolve-name
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --windowed --onefile --name "Calculator" ^
          --hidden-import pkgutil ^
          --hidden-import PyQt6.QtCore ^
          --hidden-import PyQt6.QtWidgets ^
          --hidden-import PyQt6.QtGui ^
          calculator_qt.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Calculator-Windows
        path: dist/Calculator.exe
        retention-days: 5
